config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	member do
  		put "like" => "posts#vote"
  	end
  	resources :comments
  end
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_votable
	has_many :comments, dependent: :destroy
	belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authenticate_user!, only: [:new, :vote], except: [:index, :show]
  respond_to :js, :json
 
  # GET /posts
  # GET /posts.json
  def index
    if params[:title]
    @posts = Post.where('title LIKE ?',  "%#{params[:title]}%")
     render json: { posts: @posts,status: 'OK', message: 'success'}
    else
    @posts = Post.all.paginate(:page => params[:page], :per_page => 1 ).order("created_at DESC")
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def vote
    if !current_user.liked? @post
      @post.like_by current_user
    else current_user.liked? @post
    @post.unliked_by current_user
    end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<script>
function sharePost(postid){
  //alert(postid)
  $("#share_post_id").val( postid );
  $('#myModal').modal('show');
  $('#myModal').on('shown.bs.modal', function() {
    $('#myModal').find('.modal-body #share_post_id').val(postid);  
 });
}
</script>


<div class= "pull-right">
<div class="row">
<div class=" col-md-8">
<%= form_tag(posts_path, method: :get) do %>
  Post <%= text_field_tag :title, params[:title], :key => "value", :onkeyup =>"myFunction(this.value)" %>
  <%#= submit_tag 'Search', name: nil %>
<% end %>
</div>
<div class=" col-md-4">
<%= link_to 'Home', posts_path %> | <%= link_to 'New Post', new_post_path %>
</div>
</div>
</div>
<p id="notice"><%= notice %></p>
<% @posts.each do |post| %>
<div id="search">
    <h3><%= post.title %> </h3><p><b>User:</b><%= post.user.email %></p>
    <p><%= post.body %></p>
    <% if user_signed_in? %>
    <%= link_to 'Read Post', post%> |
     <span id="id-<%= post.id %>" onclick="sharePost('<%= post.id %>')">
      <input type="hidden" class="post_id" id="post_id" name="post_id" value="<%= post.id %>">
     <%= link_to 'Share Post', new_share_path, :remote => true, class: "share_modal", data: {toggle: "modal", target: "#modal"} %></span>
    <% else %>
    <%= link_to 'Please sign in For read the post', new_user_session_path%>
    <% end %>  
    <hr>
</div>
<% end %>
<div id="search1"></div>
<div class= "pull-right">
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails%>
</div>
  
 

 <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body a-unique-class">
           
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Home', posts_path %> | <%= link_to 'New Post', new_post_path %>
<h3>
  <strong>Title:</strong>
  <%= @post.title %>
</h3>

<p>
  <strong></strong>
  <%= @post.body %>
  <%= link_to like_post_path(@post), class:"like-btn", method: :put, remote: :true do %>

<div style="color:black">
  <p class="btn-clr"><i class="fa fa-thumbs-o-up fa-3x"></i></p>
</div>

<span class="likes-count" id="post-<%= @post.id %>">
  <%= @post.get_upvotes.size %>
</span>

<% end %>
</p>

<br>
<h2> <%= @post.comments.count %> Comments</h2>
		<div class="appendCmnt"><%= render @post.comments %></div>
    <p ></p>
		<h3> Add a comments: </h3>
		<%= render 'comments/form' %>
<br>
<% if @post.user == current_user %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Delete', post_path, method: :delete, data: { confirm: "Are You Sure Want to delete"}%>
<% end %>

app/views/posts/vote.js.erb
<% if current_user.liked? @post %>
  $('.like-btn').addClass('liked');
  $('.btn-clr').css('color', 'red');
<% else %>
  $('.like-btn').removeClass('liked');
  $('.btn-clr').css('color', 'black');
<% end %> 
$("#post-<%= @post.id %>").addClass("liked").html('<%= @post.get_upvotes.size %>');/*$(documnet).ready(function(){
$('.like-count').html("<%= @post.get_upvotes.size %>");
});*/